<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('cities')->delete();
    	$cities = array(
	        array('name' => "Leticia",'department_id' => 1),
	        array('name' => "El Encanto",'department_id' => 1),
	        array('name' => "La Chorrera",'department_id' => 1),
	        array('name' => "La Pedrera",'department_id' => 1),
	        array('name' => "La Victoria",'department_id' => 1),
	        array('name' => "Miriti-Parana",'department_id' => 1),
	        array('name' => "Puerto Alegria",'department_id' => 1),
	        array('name' => "Puerto Arica",'department_id' => 1),
	        array('name' => "Puerto Narino",'department_id' => 1),
	        array('name' => "Santander",'department_id' => 1),
	        array('name' => "Tarapaca",'department_id' => 1),

			array('name' => "Abejorral",'department_id' => 2),
			array('name' => "Abriaqui",'department_id' => 2),
			array('name' => "Alejandria",'department_id' => 2),
			array('name' => "Amaga",'department_id' => 2),
			array('name' => "Amalfi",'department_id' => 2),
			array('name' => "Andes",'department_id' => 2),
			array('name' => "Angelopolis",'department_id' => 2),
			array('name' => "Angostura",'department_id' => 2),
			array('name' => "Anori",'department_id' => 2),
			array('name' => "Antioquia",'department_id' => 2),
			array('name' => "Anza",'department_id' => 2),
			array('name' => "Apartado",'department_id' => 2),
			array('name' => "Arboletes",'department_id' => 2),
			array('name' => "Argelia",'department_id' => 2),
			array('name' => "Armenia",'department_id' => 2),
			array('name' => "Barbosa",'department_id' => 2),
			array('name' => "Bello",'department_id' => 2),
			array('name' => "Belmira",'department_id' => 2),
			array('name' => "Betania",'department_id' => 2),
			array('name' => "Betulia",'department_id' => 2),
			array('name' => "Bolivar",'department_id' => 2),
			array('name' => "Briceno",'department_id' => 2),
			array('name' => "Buritica",'department_id' => 2),
			array('name' => "Caceres",'department_id' => 2),
			array('name' => "Caicedo",'department_id' => 2),
			array('name' => "Caldas",'department_id' => 2),
			array('name' => "Campamento",'department_id' => 2),
			array('name' => "Canasgordas",'department_id' => 2),
			array('name' => "Caracoli",'department_id' => 2),
			array('name' => "Caramanta",'department_id' => 2),
			array('name' => "Carepa",'department_id' => 2),
			array('name' => "Carmen de Viboral",'department_id' => 2),
			array('name' => "Carolina",'department_id' => 2),
			array('name' => "Caucasia",'department_id' => 2),
			array('name' => "Chigorodo",'department_id' => 2),
			array('name' => "Cisneros",'department_id' => 2),
			array('name' => "Cocorna",'department_id' => 2),
			array('name' => "Concepcion",'department_id' => 2),
			array('name' => "Concordia",'department_id' => 2),
			array('name' => "Copacabana",'department_id' => 2),
			array('name' => "Dabeiba",'department_id' => 2),
			array('name' => "Don Matias",'department_id' => 2),
			array('name' => "Ebejico",'department_id' => 2),
			array('name' => "El Bagre",'department_id' => 2),
			array('name' => "Entrerrios",'department_id' => 2),
			array('name' => "Envigado",'department_id' => 2),
			array('name' => "Fredonia",'department_id' => 2),
			array('name' => "Frontino",'department_id' => 2),
			array('name' => "Giraldo",'department_id' => 2),
			array('name' => "Girardota",'department_id' => 2),
			array('name' => "Gomez Plata",'department_id' => 2),
			array('name' => "Granada",'department_id' => 2),
			array('name' => "Guadalupe",'department_id' => 2),
			array('name' => "Guarne",'department_id' => 2),
			array('name' => "Guatape",'department_id' => 2),
			array('name' => "Heliconia",'department_id' => 2),
			array('name' => "Hispania",'department_id' => 2),
			array('name' => "Itagui",'department_id' => 2),
			array('name' => "Ituango",'department_id' => 2),
			array('name' => "Jardin",'department_id' => 2),
			array('name' => "Jerico",'department_id' => 2),
			array('name' => "La Ceja",'department_id' => 2),
			array('name' => "La Estrella",'department_id' => 2),
			array('name' => "La Pintada",'department_id' => 2),
			array('name' => "La Union",'department_id' => 2),
			array('name' => "Liborina",'department_id' => 2),
			array('name' => "Maceo",'department_id' => 2),
			array('name' => "Marinilla",'department_id' => 2),
			array('name' => "Medellin",'department_id' => 2),
			array('name' => "Montebello",'department_id' => 2),
			array('name' => "Murindo",'department_id' => 2),
			array('name' => "Mutata",'department_id' => 2),
			array('name' => "Narino",'department_id' => 2),
			array('name' => "Nechi",'department_id' => 2),
			array('name' => "Necocli",'department_id' => 2),
			array('name' => "Olaya",'department_id' => 2),
			array('name' => "Penol",'department_id' => 2),
			array('name' => "Peque",'department_id' => 2),
			array('name' => "Pueblorrico",'department_id' => 2),
			array('name' => "Puerto Berrio",'department_id' => 2),
			array('name' => "Puerto Nare",'department_id' => 2),
			array('name' => "Puerto Triunfo",'department_id' => 2),
			array('name' => "Remedios",'department_id' => 2),
			array('name' => "Retiro",'department_id' => 2),
			array('name' => "Rionegro",'department_id' => 2),
			array('name' => "Sabanalarga",'department_id' => 2),
			array('name' => "Sabaneta",'department_id' => 2),
			array('name' => "Salgar",'department_id' => 2),
			array('name' => "San Andres",'department_id' => 2),
			array('name' => "San Carlos",'department_id' => 2),
			array('name' => "San Francisco",'department_id' => 2),
			array('name' => "San Jeronimo",'department_id' => 2),
			array('name' => "San Jose de la Montana",'department_id' => 2),
			array('name' => "San Juan de Uraba",'department_id' => 2),
			array('name' => "San Luis",'department_id' => 2),
			array('name' => "San Pedro",'department_id' => 2),
			array('name' => "San Pedro de Uraba",'department_id' => 2),
			array('name' => "San Rafael",'department_id' => 2),
			array('name' => "San Roque",'department_id' => 2),
			array('name' => "San Vicente",'department_id' => 2),
			array('name' => "Santa Barbara",'department_id' => 2),
			array('name' => "Santa Rosa de Osos",'department_id' => 2),
			array('name' => "Santo Domingo",'department_id' => 2),
			array('name' => "Santuario",'department_id' => 2),
			array('name' => "Segovia",'department_id' => 2),
			array('name' => "Sonson",'department_id' => 2),
			array('name' => "Sopetran",'department_id' => 2),
			array('name' => "Tamesis",'department_id' => 2),
			array('name' => "Taraza",'department_id' => 2),
			array('name' => "Tarso",'department_id' => 2),
			array('name' => "Titiribi",'department_id' => 2),
			array('name' => "Toledo",'department_id' => 2),
			array('name' => "Turbo",'department_id' => 2),
			array('name' => "Uramita",'department_id' => 2),
			array('name' => "Urrao",'department_id' => 2),
			array('name' => "Valdivia",'department_id' => 2),
			array('name' => "Valparaiso",'department_id' => 2),
			array('name' => "Vegachi",'department_id' => 2),
			array('name' => "Venecia",'department_id' => 2),
			array('name' => "Vigia del Fuerte",'department_id' => 2),
			array('name' => "Yali",'department_id' => 2),
			array('name' => "Yarumal",'department_id' => 2),
			array('name' => "Yolombo",'department_id' => 2),
			array('name' => "Yondo",'department_id' => 2),
			array('name' => "Zaragoza",'department_id' => 2),
			array('name' => "Arauca",'department_id' => 3),
			array('name' => "Arauquita",'department_id' => 3),
			array('name' => "Cravo Norte",'department_id' => 3),
			array('name' => "Fortul",'department_id' => 3),
			array('name' => "Puerto Rondon",'department_id' => 3),
			array('name' => "Saravena",'department_id' => 3),
			array('name' => "Tame",'department_id' => 3),
			array('name' => "Baranoa",'department_id' => 4),
			array('name' => "Barranquilla",'department_id' => 4),
			array('name' => "Campo de la Cruz",'department_id' => 4),
			array('name' => "Candelaria",'department_id' => 4),
			array('name' => "Galapa",'department_id' => 4),
			array('name' => "Juan de Acosta",'department_id' => 4),
			array('name' => "Luruaco",'department_id' => 4),
			array('name' => "Malambo",'department_id' => 4),
			array('name' => "Manati",'department_id' => 4),
			array('name' => "Palmar de Varela",'department_id' => 4),
			array('name' => "Piojo",'department_id' => 4),
			array('name' => "Polo Nuevo",'department_id' => 4),
			array('name' => "Ponedera",'department_id' => 4),
			array('name' => "Puerto Colombia",'department_id' => 4),
			array('name' => "Repelon",'department_id' => 4),
			array('name' => "Sabanagrande",'department_id' => 4),
			array('name' => "Sabanalarga",'department_id' => 4),
			array('name' => "Santa Lucia",'department_id' => 4),
			array('name' => "Santo Tomas",'department_id' => 4),
			array('name' => "Soledad",'department_id' => 4),
			array('name' => "Suan",'department_id' => 4),
			array('name' => "Tubara",'department_id' => 4),
			array('name' => "Usiacuri",'department_id' => 4),
			array('name' => "Bogota",'department_id' => 5),
			array('name' => "Achi",'department_id' => 6),
			array('name' => "Altos del Rosario",'department_id' => 6),
			array('name' => "Arenal",'department_id' => 6),
			array('name' => "Arjona",'department_id' => 6),
			array('name' => "Arroyohondo",'department_id' => 6),
			array('name' => "Barranco de Loba",'department_id' => 6),
			array('name' => "Calamar",'department_id' => 6),
			array('name' => "Cantagallo",'department_id' => 6),
			array('name' => "Cartagena",'department_id' => 6),
			array('name' => "Cicuco",'department_id' => 6),
			array('name' => "Clemencia",'department_id' => 6),
			array('name' => "Cordoba",'department_id' => 6),
			array('name' => "El Carmen de Bolivar",'department_id' => 6),
			array('name' => "El Guamo",'department_id' => 6),
			array('name' => "El Penon",'department_id' => 6),
			array('name' => "Hatillo de Loba",'department_id' => 6),
			array('name' => "Magangue",'department_id' => 6),
			array('name' => "Mahates",'department_id' => 6),
			array('name' => "Margarita",'department_id' => 6),
			array('name' => "Maria la Baja",'department_id' => 6),
			array('name' => "Mompos",'department_id' => 6),
			array('name' => "Montecristo",'department_id' => 6),
			array('name' => "Morales",'department_id' => 6),
			array('name' => "Pinillos",'department_id' => 6),
			array('name' => "Regidor",'department_id' => 6),
			array('name' => "Rio Viejo",'department_id' => 6),
			array('name' => "San Cristobal",'department_id' => 6),
			array('name' => "San Estanislao",'department_id' => 6),
			array('name' => "San Fernando",'department_id' => 6),
			array('name' => "San Jacinto",'department_id' => 6),
			array('name' => "San Jacinto del Cauca",'department_id' => 6),
			array('name' => "San Juan Nepomuceno",'department_id' => 6),
			array('name' => "San Martin de Loba",'department_id' => 6),
			array('name' => "San Pablo",'department_id' => 6),
			array('name' => "Santa Catalina",'department_id' => 6),
			array('name' => "Santa Rosa",'department_id' => 6),
			array('name' => "Santa Rosa del Sur",'department_id' => 6),
			array('name' => "Simiti",'department_id' => 6),
			array('name' => "Soplaviento",'department_id' => 6),
			array('name' => "Talaigua Nuevo",'department_id' => 6),
			array('name' => "Tiquisio",'department_id' => 6),
			array('name' => "Turbaco",'department_id' => 6),
			array('name' => "Turbana",'department_id' => 6),
			array('name' => "Villanueva",'department_id' => 6),
			array('name' => "Zambrano",'department_id' => 6),
			array('name' => "Almeida",'department_id' => 7),
			array('name' => "Aquitania",'department_id' => 7),
			array('name' => "Arcabuco",'department_id' => 7),
			array('name' => "Belen",'department_id' => 7),
			array('name' => "Berbeo",'department_id' => 7),
			array('name' => "Beteitiva",'department_id' => 7),
			array('name' => "Boavita",'department_id' => 7),
			array('name' => "Boyaca",'department_id' => 7),
			array('name' => "Briceno",'department_id' => 7),
			array('name' => "Buenavista",'department_id' => 7),
			array('name' => "Busbanza",'department_id' => 7),
			array('name' => "Caldas",'department_id' => 7),
			array('name' => "Campohermoso",'department_id' => 7),
			array('name' => "Cerinza",'department_id' => 7),
			array('name' => "Chinavita",'department_id' => 7),
			array('name' => "Chiquinquira",'department_id' => 7),
			array('name' => "Chiquiza",'department_id' => 7),
			array('name' => "Chiscas",'department_id' => 7),
			array('name' => "Chita",'department_id' => 7),
			array('name' => "Chitaraque",'department_id' => 7),
			array('name' => "Chivata",'department_id' => 7),
			array('name' => "Chivor",'department_id' => 7),
			array('name' => "Cienega",'department_id' => 7),
			array('name' => "Combita",'department_id' => 7),
			array('name' => "Coper",'department_id' => 7),
			array('name' => "Corrales",'department_id' => 7),
			array('name' => "Covarachia",'department_id' => 7),
			array('name' => "Cubara",'department_id' => 7),
			array('name' => "Cucaita",'department_id' => 7),
			array('name' => "Cuitiva",'department_id' => 7),
			array('name' => "Duitama",'department_id' => 7),
			array('name' => "El Cocuy",'department_id' => 7),
			array('name' => "El Espino",'department_id' => 7),
			array('name' => "Firavitoba",'department_id' => 7),
			array('name' => "Floresta",'department_id' => 7),
			array('name' => "Gachantiva",'department_id' => 7),
			array('name' => "Gameza",'department_id' => 7),
			array('name' => "Garagoa",'department_id' => 7),
			array('name' => "Guacamayas",'department_id' => 7),
			array('name' => "Guateque",'department_id' => 7),
			array('name' => "Guayata",'department_id' => 7),
			array('name' => "Guican",'department_id' => 7),
			array('name' => "Iza",'department_id' => 7),
			array('name' => "Jenesano",'department_id' => 7),
			array('name' => "Jerico",'department_id' => 7),
			array('name' => "La Capilla",'department_id' => 7),
			array('name' => "La Uvita",'department_id' => 7),
			array('name' => "La Victoria",'department_id' => 7),
			array('name' => "Labranzagrande",'department_id' => 7),
			array('name' => "Leiva",'department_id' => 7),
			array('name' => "Macanal",'department_id' => 7),
			array('name' => "Maripi",'department_id' => 7),
			array('name' => "Miraflores",'department_id' => 7),
			array('name' => "Mongua",'department_id' => 7),
			array('name' => "Mongui",'department_id' => 7),
			array('name' => "Moniquira",'department_id' => 7),
			array('name' => "Motavita",'department_id' => 7),
			array('name' => "Muzo",'department_id' => 7),
			array('name' => "Nobsa",'department_id' => 7),
			array('name' => "Nuevo Colon",'department_id' => 7),
			array('name' => "Oicata",'department_id' => 7),
			array('name' => "Otanche",'department_id' => 7),
			array('name' => "Pachavita",'department_id' => 7),
			array('name' => "Paez",'department_id' => 7),
			array('name' => "Paipa",'department_id' => 7),
			array('name' => "Pajarito",'department_id' => 7),
			array('name' => "Panqueba",'department_id' => 7),
			array('name' => "Pauna",'department_id' => 7),
			array('name' => "Paya",'department_id' => 7),
			array('name' => "Paz del Rio",'department_id' => 7),
			array('name' => "Pesca",'department_id' => 7),
			array('name' => "Pisba",'department_id' => 7),
			array('name' => "Puerto Boyaca",'department_id' => 7),
			array('name' => "Quipama",'department_id' => 7),
			array('name' => "Ramiriqui",'department_id' => 7),
			array('name' => "Raquira",'department_id' => 7),
			array('name' => "Rondon",'department_id' => 7),
			array('name' => "Saboya",'department_id' => 7),
			array('name' => "Sachica",'department_id' => 7),
			array('name' => "Samaca",'department_id' => 7),
			array('name' => "San Eduardo",'department_id' => 7),
			array('name' => "San Jose de Pare",'department_id' => 7),
			array('name' => "San Luis de Gaceno",'department_id' => 7),
			array('name' => "San Mateo",'department_id' => 7),
			array('name' => "San Miguel de Sema",'department_id' => 7),
			array('name' => "San Pablo de Borbur",'department_id' => 7),
			array('name' => "Santa Maria",'department_id' => 7),
			array('name' => "Santa Rosa de Viterbo",'department_id' => 7),
			array('name' => "Santa Sofia",'department_id' => 7),
			array('name' => "Santana",'department_id' => 7),
			array('name' => "Sativanorte",'department_id' => 7),
			array('name' => "Sativasur",'department_id' => 7),
			array('name' => "Siachoque",'department_id' => 7),
			array('name' => "Soata",'department_id' => 7),
			array('name' => "Socha",'department_id' => 7),
			array('name' => "Socota",'department_id' => 7),
			array('name' => "Sogamoso",'department_id' => 7),
			array('name' => "Somondoco",'department_id' => 7),
			array('name' => "Sora",'department_id' => 7),
			array('name' => "Soraca",'department_id' => 7),
			array('name' => "Sotaquira",'department_id' => 7),
			array('name' => "Susacon",'department_id' => 7),
			array('name' => "Sutamarchan",'department_id' => 7),
			array('name' => "Sutatenza",'department_id' => 7),
			array('name' => "Tasco",'department_id' => 7),
			array('name' => "Tenza",'department_id' => 7),
			array('name' => "Tibana",'department_id' => 7),
			array('name' => "Tibasosa",'department_id' => 7),
			array('name' => "Tinjaca",'department_id' => 7),
			array('name' => "Tipacoque",'department_id' => 7),
			array('name' => "Toca",'department_id' => 7),
			array('name' => "Togui",'department_id' => 7),
			array('name' => "Topaga",'department_id' => 7),
			array('name' => "Tota",'department_id' => 7),
			array('name' => "Tunja",'department_id' => 7),
			array('name' => "Tunungua",'department_id' => 7),
			array('name' => "Turmeque",'department_id' => 7),
			array('name' => "Tuta",'department_id' => 7),
			array('name' => "Tutasa",'department_id' => 7),
			array('name' => "Umbita",'department_id' => 7),
			array('name' => "Ventaquemada",'department_id' => 7),
			array('name' => "Viracacha",'department_id' => 7),
			array('name' => "Zetaquira",'department_id' => 7),
			array('name' => "Aguadas",'department_id' => 8),
			array('name' => "Anserma",'department_id' => 8),
			array('name' => "Aranzazu",'department_id' => 8),
			array('name' => "Belalcazar",'department_id' => 8),
			array('name' => "Chinchina",'department_id' => 8),
			array('name' => "Filadelfia",'department_id' => 8),
			array('name' => "La Dorada",'department_id' => 8),
			array('name' => "La Merced",'department_id' => 8),
			array('name' => "Manizales",'department_id' => 8),
			array('name' => "Manzanares",'department_id' => 8),
			array('name' => "Marmato",'department_id' => 8),
			array('name' => "Marquetalia",'department_id' => 8),
			array('name' => "Marulanda",'department_id' => 8),
			array('name' => "Neira",'department_id' => 8),
			array('name' => "Norcasia",'department_id' => 8),
			array('name' => "Pacora",'department_id' => 8),
			array('name' => "Palestina",'department_id' => 8),
			array('name' => "Pensilvania",'department_id' => 8),
			array('name' => "Riosucio",'department_id' => 8),
			array('name' => "Risaralda",'department_id' => 8),
			array('name' => "Salamina",'department_id' => 8),
			array('name' => "Samana",'department_id' => 8),
			array('name' => "San Jose",'department_id' => 8),
			array('name' => "Supia",'department_id' => 8),
			array('name' => "Victoria",'department_id' => 8),
			array('name' => "Villamaria",'department_id' => 8),
			array('name' => "Viterbo",'department_id' => 8),
			array('name' => "Albania",'department_id' => 9),
			array('name' => "Belen Andaquies",'department_id' => 9),
			array('name' => "Cartagena del Chaira",'department_id' => 9),
			array('name' => "Curillo",'department_id' => 9),
			array('name' => "El Doncello",'department_id' => 9),
			array('name' => "El Paujil",'department_id' => 9),
			array('name' => "Florencia",'department_id' => 9),
			array('name' => "La Montanita",'department_id' => 9),
			array('name' => "Milan",'department_id' => 9),
			array('name' => "Morelia",'department_id' => 9),
			array('name' => "Puerto Rico",'department_id' => 9),
			array('name' => "San Jose de Fragua",'department_id' => 9),
			array('name' => "San Vicente del Caguan",'department_id' => 9),
			array('name' => "Solano",'department_id' => 9),
			array('name' => "Solita",'department_id' => 9),
			array('name' => "Valparaiso",'department_id' => 9),
			array('name' => "Aguazul",'department_id' => 10),
			array('name' => "Chameza",'department_id' => 10),
			array('name' => "Hato Corozal",'department_id' => 10),
			array('name' => "La Salina",'department_id' => 10),
			array('name' => "Mani",'department_id' => 10),
			array('name' => "Monterrey",'department_id' => 10),
			array('name' => "Nunchia",'department_id' => 10),
			array('name' => "Orocue",'department_id' => 10),
			array('name' => "Paz de Ariporo",'department_id' => 10),
			array('name' => "Pore",'department_id' => 10),
			array('name' => "Recetor",'department_id' => 10),
			array('name' => "Sabanalarga",'department_id' => 10),
			array('name' => "Sacama",'department_id' => 10),
			array('name' => "San Luis de Palenque",'department_id' => 10),
			array('name' => "Tamara",'department_id' => 10),
			array('name' => "Tauramena",'department_id' => 10),
			array('name' => "Trinidad",'department_id' => 10),
			array('name' => "Villanueva",'department_id' => 10),
			array('name' => "Yopal",'department_id' => 10),
			array('name' => "Almaguer",'department_id' => 11),
			array('name' => "Argelia",'department_id' => 11),
			array('name' => "Balboa",'department_id' => 11),
			array('name' => "Bolivar",'department_id' => 11),
			array('name' => "Buenos Aires",'department_id' => 11),
			array('name' => "Cajibio",'department_id' => 11),
			array('name' => "Caldono",'department_id' => 11),
			array('name' => "Caloto",'department_id' => 11),
			array('name' => "Corinto",'department_id' => 11),
			array('name' => "El Bordo",'department_id' => 11),
			array('name' => "El Tambo",'department_id' => 11),
			array('name' => "Florencia",'department_id' => 11),
			array('name' => "Guapi",'department_id' => 11),
			array('name' => "Inza",'department_id' => 11),
			array('name' => "Jambalo",'department_id' => 11),
			array('name' => "La Sierra",'department_id' => 11),
			array('name' => "La Vega",'department_id' => 11),
			array('name' => "Lopez",'department_id' => 11),
			array('name' => "Mercaderes",'department_id' => 11),
			array('name' => "Miranda",'department_id' => 11),
			array('name' => "Morales",'department_id' => 11),
			array('name' => "Padilla",'department_id' => 11),
			array('name' => "Paez",'department_id' => 11),
			array('name' => "Piamonte",'department_id' => 11),
			array('name' => "Piendamo",'department_id' => 11),
			array('name' => "Popayan",'department_id' => 11),
			array('name' => "Puerto Tejada",'department_id' => 11),
			array('name' => "Purace",'department_id' => 11),
			array('name' => "Rosas",'department_id' => 11),
			array('name' => "San Sebastian",'department_id' => 11),
			array('name' => "Santa Rosa",'department_id' => 11),
			array('name' => "Santander de Quilichao",'department_id' => 11),
			array('name' => "Silvia",'department_id' => 11),
			array('name' => "Sotara",'department_id' => 11),
			array('name' => "Suarez",'department_id' => 11),
			array('name' => "Sucre",'department_id' => 11),
			array('name' => "Timbio",'department_id' => 11),
			array('name' => "Timbiqui",'department_id' => 11),
			array('name' => "Toribio",'department_id' => 11),
			array('name' => "Totoro",'department_id' => 11),
			array('name' => "Villa Rica",'department_id' => 11),
			array('name' => "Aguachica",'department_id' => 12),
			array('name' => "Agustin Codazzi",'department_id' => 12),
			array('name' => "Astrea",'department_id' => 12),
			array('name' => "Becerril",'department_id' => 12),
			array('name' => "Bosconia",'department_id' => 12),
			array('name' => "Chimichagua",'department_id' => 12),
			array('name' => "Chiriguana",'department_id' => 12),
			array('name' => "Curumani",'department_id' => 12),
			array('name' => "El Copey",'department_id' => 12),
			array('name' => "El Paso",'department_id' => 12),
			array('name' => "Gamarra",'department_id' => 12),
			array('name' => "Gonzalez",'department_id' => 12),
			array('name' => "La Gloria",'department_id' => 12),
			array('name' => "La Jagua Ibirico",'department_id' => 12),
			array('name' => "Manaure",'department_id' => 12),
			array('name' => "Pailitas",'department_id' => 12),
			array('name' => "Pelaya",'department_id' => 12),
			array('name' => "Pueblo Bello",'department_id' => 12),
			array('name' => "Rio de Oro",'department_id' => 12),
			array('name' => "Robles la Paz",'department_id' => 12),
			array('name' => "San Alberto",'department_id' => 12),
			array('name' => "San Diego",'department_id' => 12),
			array('name' => "San Martin",'department_id' => 12),
			array('name' => "Tamalameque",'department_id' => 12),
			array('name' => "Valledupar",'department_id' => 12),
			array('name' => "Acandi",'department_id' => 13),
			array('name' => "Alto Baudo",'department_id' => 13),
			array('name' => "Atrato",'department_id' => 13),
			array('name' => "Bagado",'department_id' => 13),
			array('name' => "Bahia Solano",'department_id' => 13),
			array('name' => "Bajo Baudo",'department_id' => 13),
			array('name' => "Bojaya",'department_id' => 13),
			array('name' => "Canton de San Pablo",'department_id' => 13),
			array('name' => "Carmen del Darien",'department_id' => 13),
			array('name' => "Certegui",'department_id' => 13),
			array('name' => "Condoto",'department_id' => 13),
			array('name' => "El Carmen",'department_id' => 13),
			array('name' => "Istmina",'department_id' => 13),
			array('name' => "Jurado",'department_id' => 13),
			array('name' => "Litoral del San Juan",'department_id' => 13),
			array('name' => "Lloro",'department_id' => 13),
			array('name' => "Medio Atrato",'department_id' => 13),
			array('name' => "Medio Baudo",'department_id' => 13),
			array('name' => "Medio San Juan",'department_id' => 13),
			array('name' => "Novita",'department_id' => 13),
			array('name' => "Nuqui",'department_id' => 13),
			array('name' => "Quibdo",'department_id' => 13),
			array('name' => "Rio Iro",'department_id' => 13),
			array('name' => "Rio Quito",'department_id' => 13),
			array('name' => "Riosucio",'department_id' => 13),
			array('name' => "San Jose del Palmar",'department_id' => 13),
			array('name' => "Sipi",'department_id' => 13),
			array('name' => "Tado",'department_id' => 13),
			array('name' => "Unguia",'department_id' => 13),
			array('name' => "Union Panamericana",'department_id' => 13),
			array('name' => "Ayapel",'department_id' => 14),
			array('name' => "Buenavista",'department_id' => 14),
			array('name' => "Canalete",'department_id' => 14),
			array('name' => "Cerete",'department_id' => 14),
			array('name' => "Chima",'department_id' => 14),
			array('name' => "Chinu",'department_id' => 14),
			array('name' => "Cienaga de Oro",'department_id' => 14),
			array('name' => "Cotorra",'department_id' => 14),
			array('name' => "La Apartada",'department_id' => 14),
			array('name' => "Lorica",'department_id' => 14),
			array('name' => "Los Cordobas",'department_id' => 14),
			array('name' => "Momil",'department_id' => 14),
			array('name' => "Monitos",'department_id' => 14),
			array('name' => "Montelibano",'department_id' => 14),
			array('name' => "Monteria",'department_id' => 14),
			array('name' => "Planeta Rica",'department_id' => 14),
			array('name' => "Pueblo Nuevo",'department_id' => 14),
			array('name' => "Puerto Escondido",'department_id' => 14),
			array('name' => "Puerto Libertador",'department_id' => 14),
			array('name' => "Purisima",'department_id' => 14),
			array('name' => "Sahagun",'department_id' => 14),
			array('name' => "San Andres Sotavento",'department_id' => 14),
			array('name' => "San Antero",'department_id' => 14),
			array('name' => "San Bernardo Viento",'department_id' => 14),
			array('name' => "San Carlos",'department_id' => 14),
			array('name' => "San Pelayo",'department_id' => 14),
			array('name' => "Tierralta",'department_id' => 14),
			array('name' => "Valencia",'department_id' => 14),
			array('name' => "Agua de Dios",'department_id' => 15),
			array('name' => "Alban",'department_id' => 15),
			array('name' => "Anapoima",'department_id' => 15),
			array('name' => "Anolaima",'department_id' => 15),
			array('name' => "Arbelaez",'department_id' => 15),
			array('name' => "Beltran",'department_id' => 15),
			array('name' => "Bituima",'department_id' => 15),
			array('name' => "Bojaca",'department_id' => 15),
			array('name' => "Cabrera",'department_id' => 15),
			array('name' => "Cachipay",'department_id' => 15),
			array('name' => "Cajica",'department_id' => 15),
			array('name' => "Caparrapi",'department_id' => 15),
			array('name' => "Caqueza",'department_id' => 15),
			array('name' => "Carmen de Carupa",'department_id' => 15),
			array('name' => "Chaguani",'department_id' => 15),
			array('name' => "Chia",'department_id' => 15),
			array('name' => "Chipaque",'department_id' => 15),
			array('name' => "Choachi",'department_id' => 15),
			array('name' => "Choconta",'department_id' => 15),
			array('name' => "Cogua",'department_id' => 15),
			array('name' => "Cota",'department_id' => 15),
			array('name' => "Cucunuba",'department_id' => 15),
			array('name' => "El Colegio",'department_id' => 15),
			array('name' => "El Penon",'department_id' => 15),
			array('name' => "El Rosal",'department_id' => 15),
			array('name' => "Facatativa",'department_id' => 15),
			array('name' => "Fomeque",'department_id' => 15),
			array('name' => "Fosca",'department_id' => 15),
			array('name' => "Funza",'department_id' => 15),
			array('name' => "Fuquene",'department_id' => 15),
			array('name' => "Fusagasuga",'department_id' => 15),
			array('name' => "Gachala",'department_id' => 15),
			array('name' => "Gachancipa",'department_id' => 15),
			array('name' => "Gacheta",'department_id' => 15),
			array('name' => "Gama",'department_id' => 15),
			array('name' => "Girardot",'department_id' => 15),
			array('name' => "Granada",'department_id' => 15),
			array('name' => "Guacheta",'department_id' => 15),
			array('name' => "Guaduas",'department_id' => 15),
			array('name' => "Guasca",'department_id' => 15),
			array('name' => "Guataqui",'department_id' => 15),
			array('name' => "Guatavita",'department_id' => 15),
			array('name' => "Guayabal de Siquima",'department_id' => 15),
			array('name' => "Guayabetal",'department_id' => 15),
			array('name' => "Gutierrez",'department_id' => 15),
			array('name' => "Jerusalen",'department_id' => 15),
			array('name' => "Junin",'department_id' => 15),
			array('name' => "La Calera",'department_id' => 15),
			array('name' => "La Mesa",'department_id' => 15),
			array('name' => "La Palma",'department_id' => 15),
			array('name' => "La Pena",'department_id' => 15),
			array('name' => "La Vega",'department_id' => 15),
			array('name' => "Lenguazaque",'department_id' => 15),
			array('name' => "Macheta",'department_id' => 15),
			array('name' => "Madrid",'department_id' => 15),
			array('name' => "Manta",'department_id' => 15),
			array('name' => "Medina",'department_id' => 15),
			array('name' => "Mosquera",'department_id' => 15),
			array('name' => "Narino",'department_id' => 15),
			array('name' => "Nemocon",'department_id' => 15),
			array('name' => "Nilo",'department_id' => 15),
			array('name' => "Nimaima",'department_id' => 15),
			array('name' => "Nocaima",'department_id' => 15),
			array('name' => "Ospina Perez",'department_id' => 15),
			array('name' => "Pacho",'department_id' => 15),
			array('name' => "Paime",'department_id' => 15),
			array('name' => "Pandi",'department_id' => 15),
			array('name' => "Paratebueno",'department_id' => 15),
			array('name' => "Pasca",'department_id' => 15),
			array('name' => "Puerto Salgar",'department_id' => 15),
			array('name' => "Puli",'department_id' => 15),
			array('name' => "Quebradanegra",'department_id' => 15),
			array('name' => "Quetame",'department_id' => 15),
			array('name' => "Quipile",'department_id' => 15),
			array('name' => "Rafael Reyes",'department_id' => 15),
			array('name' => "Ricaurte",'department_id' => 15),
			array('name' => "San Antonio del Tequendama",'department_id' => 15),
			array('name' => "San Bernardo",'department_id' => 15),
			array('name' => "San Cayetano",'department_id' => 15),
			array('name' => "San Francisco",'department_id' => 15),
			array('name' => "San Juan de Rioseco",'department_id' => 15),
			array('name' => "Sasaima",'department_id' => 15),
			array('name' => "Sesquile",'department_id' => 15),
			array('name' => "Sibate",'department_id' => 15),
			array('name' => "Silvania",'department_id' => 15),
			array('name' => "Simijaca",'department_id' => 15),
			array('name' => "Soacha",'department_id' => 15),
			array('name' => "Sopo",'department_id' => 15),
			array('name' => "Subachoque",'department_id' => 15),
			array('name' => "Suesca",'department_id' => 15),
			array('name' => "Supata",'department_id' => 15),
			array('name' => "Susa",'department_id' => 15),
			array('name' => "Sutatausa",'department_id' => 15),
			array('name' => "Tabio",'department_id' => 15),
			array('name' => "Tausa",'department_id' => 15),
			array('name' => "Tena",'department_id' => 15),
			array('name' => "Tenjo",'department_id' => 15),
			array('name' => "Tibacuy",'department_id' => 15),
			array('name' => "Tibirita",'department_id' => 15),
			array('name' => "Tocaima",'department_id' => 15),
			array('name' => "Tocancipa",'department_id' => 15),
			array('name' => "Topaipi",'department_id' => 15),
			array('name' => "Ubala",'department_id' => 15),
			array('name' => "Ubaque",'department_id' => 15),
			array('name' => "Ubate",'department_id' => 15),
			array('name' => "Une",'department_id' => 15),
			array('name' => "Utica",'department_id' => 15),
			array('name' => "Vergara",'department_id' => 15),
			array('name' => "Viani",'department_id' => 15),
			array('name' => "Villagomez",'department_id' => 15),
			array('name' => "Villapinzon",'department_id' => 15),
			array('name' => "Villeta",'department_id' => 15),
			array('name' => "Viota",'department_id' => 15),
			array('name' => "Yacopi",'department_id' => 15),
			array('name' => "Zipacon",'department_id' => 15),
			array('name' => "Zipaquira",'department_id' => 15),
			array('name' => "Barranco Mina",'department_id' => 16),
			array('name' => "Cacahual",'department_id' => 16),
			array('name' => "Inirida",'department_id' => 16),
			array('name' => "La Guadalupe",'department_id' => 16),
			array('name' => "Mapiripana",'department_id' => 16),
			array('name' => "Morichal",'department_id' => 16),
			array('name' => "Pana-Pana",'department_id' => 16),
			array('name' => "Puerto Colombia",'department_id' => 16),
			array('name' => "San Felipe",'department_id' => 16),
			
			array('name' => "Albania",'department_id' => 17),
			array('name' => "Barrancas",'department_id' => 17),
			array('name' => "Dibulla",'department_id' => 17),
			array('name' => "Distraccion",'department_id' => 17),
			array('name' => "El Molino",'department_id' => 17),
			array('name' => "Fonseca",'department_id' => 17),
			array('name' => "Hato Nuevo",'department_id' => 17),
			array('name' => "La Jagua del Pilar",'department_id' => 17),
			array('name' => "Maicao",'department_id' => 17),
			array('name' => "Manaure",'department_id' => 17),
			array('name' => "Rio Hacha",'department_id' => 17),
			array('name' => "San Juan del Cesar",'department_id' => 17),
			array('name' => "Uribia",'department_id' => 17),
			array('name' => "Urumita",'department_id' => 17),
			array('name' => "Villanueva",'department_id' => 17),

			array('name' => "Calamar",'department_id' => 18),
			array('name' => "El Retorno",'department_id' => 18),
			array('name' => "Miraflores",'department_id' => 18),
			array('name' => "San Jose del Guaviare",'department_id' => 18),

			array('name' => "Acevedo",'department_id' => 19),
			array('name' => "Agrado",'department_id' => 19),
			array('name' => "Aipe",'department_id' => 19),
			array('name' => "Algeciras",'department_id' => 19),
			array('name' => "Altamira",'department_id' => 19),
			array('name' => "Baraya",'department_id' => 19),
			array('name' => "Campoalegre",'department_id' => 19),
			array('name' => "Colombia",'department_id' => 19),
			array('name' => "Elias",'department_id' => 19),
			array('name' => "Garzon",'department_id' => 19),
			array('name' => "Gigante",'department_id' => 19),
			array('name' => "Guadalupe",'department_id' => 19),
			array('name' => "Hobo",'department_id' => 19),
			array('name' => "Iquira",'department_id' => 19),
			array('name' => "Isnos",'department_id' => 19),
			array('name' => "La Argentina",'department_id' => 19),
			array('name' => "La Plata",'department_id' => 19),
			array('name' => "Nataga",'department_id' => 19),
			array('name' => "Neiva",'department_id' => 19),
			array('name' => "Oporapa",'department_id' => 19),
			array('name' => "Paicol",'department_id' => 19),
			array('name' => "Palermo",'department_id' => 19),
			array('name' => "Palestina",'department_id' => 19),
			array('name' => "Pital",'department_id' => 19),
			array('name' => "Pitalito",'department_id' => 19),
			array('name' => "Rivera",'department_id' => 19),
			array('name' => "Saladoblanco",'department_id' => 19),
			array('name' => "San Agustin",'department_id' => 19),
			array('name' => "Santa Maria",'department_id' => 19),
			array('name' => "Suaza",'department_id' => 19),
			array('name' => "Tarqui",'department_id' => 19),
			array('name' => "Tello",'department_id' => 19),
			array('name' => "Teruel",'department_id' => 19),
			array('name' => "Tesalia",'department_id' => 19),
			array('name' => "Timana",'department_id' => 19),
			array('name' => "Villavieja",'department_id' => 19),
			array('name' => "Yaguara",'department_id' => 19),

			array('name' => "Algarrobo",'department_id' => 20),
			array('name' => "Aracataca",'department_id' => 20),
			array('name' => "Ariguani",'department_id' => 20),
			array('name' => "Cerro San Antonio",'department_id' => 20),
			array('name' => "Chivolo",'department_id' => 20),
			array('name' => "Cienaga",'department_id' => 20),
			array('name' => "Concordia",'department_id' => 20),
			array('name' => "El Banco",'department_id' => 20),
			array('name' => "El Pinon",'department_id' => 20),
			array('name' => "El Reten",'department_id' => 20),
			array('name' => "Fundacion",'department_id' => 20),
			array('name' => "Guamal",'department_id' => 20),
			array('name' => "Nueva Granada",'department_id' => 20),
			array('name' => "Pedraza",'department_id' => 20),
			array('name' => "Pijino del Carmen",'department_id' => 20),
			array('name' => "Pivijay",'department_id' => 20),
			array('name' => "Plato",'department_id' => 20),
			array('name' => "Puebloviejo",'department_id' => 20),
			array('name' => "Remolino",'department_id' => 20),
			array('name' => "Sabanas de San Angel",'department_id' => 20),
			array('name' => "Salamina",'department_id' => 20),
			array('name' => "San Sebastian",'department_id' => 20),
			array('name' => "San Zenon",'department_id' => 20),
			array('name' => "Santa Ana",'department_id' => 20),
			array('name' => "Santa Barbara de Pinto",'department_id' => 20),
			array('name' => "Santa Marta",'department_id' => 20),
			array('name' => "Sitionuevo",'department_id' => 20),
			array('name' => "Tenerife",'department_id' => 20),
			array('name' => "Zapayan",'department_id' => 20),
			array('name' => "Zona Bananera",'department_id' => 20),

			array('name' => "Acacias",'department_id' => 21),
			array('name' => "Barranca de Upia",'department_id' => 21),
			array('name' => "Cabuyaro",'department_id' => 21),
			array('name' => "Castilla la Nueva",'department_id' => 21),
			array('name' => "Cubarral",'department_id' => 21),
			array('name' => "Cumaral",'department_id' => 21),
			array('name' => "El Calvario",'department_id' => 21),
			array('name' => "El Castillo",'department_id' => 21),
			array('name' => "El Dorado",'department_id' => 21),
			array('name' => "Fuente de Oro",'department_id' => 21),
			array('name' => "Granada",'department_id' => 21),
			array('name' => "Guamal",'department_id' => 21),
			array('name' => "La Macarena",'department_id' => 21),
			array('name' => "La Uribe",'department_id' => 21),
			array('name' => "Lejanias",'department_id' => 21),
			array('name' => "Mapiripan",'department_id' => 21),
			array('name' => "Mesetas",'department_id' => 21),
			array('name' => "Puerto Concordia",'department_id' => 21),
			array('name' => "Puerto Gaitan",'department_id' => 21),
			array('name' => "Puerto Lleras",'department_id' => 21),
			array('name' => "Puerto Lopez",'department_id' => 21),
			array('name' => "Puerto Rico",'department_id' => 21),
			array('name' => "Restrepo",'department_id' => 21),
			array('name' => "San Carlos Guaroa",'department_id' => 21),
			array('name' => "San Juan de Arama",'department_id' => 21),
			array('name' => "San Juanito",'department_id' => 21),
			array('name' => "San Martin",'department_id' => 21),
			array('name' => "Villavicencio",'department_id' => 21),
			array('name' => "Vista Hermosa",'department_id' => 21),

			array('name' => "Alban",'department_id' => 22),
			array('name' => "Aldana",'department_id' => 22),
			array('name' => "Ancuya",'department_id' => 22),
			array('name' => "Arboleda",'department_id' => 22),
			array('name' => "Barbacoas",'department_id' => 22),
			array('name' => "Belen",'department_id' => 22),
			array('name' => "Buesaco",'department_id' => 22),
			array('name' => "Chachagui",'department_id' => 22),
			array('name' => "Colon",'department_id' => 22),
			array('name' => "Consaca",'department_id' => 22),
			array('name' => "Contadero",'department_id' => 22),
			array('name' => "Cordoba",'department_id' => 22),
			array('name' => "Cuaspud",'department_id' => 22),
			array('name' => "Cumbal",'department_id' => 22),
			array('name' => "Cumbitara",'department_id' => 22),
			array('name' => "El Charco",'department_id' => 22),
			array('name' => "El Penol",'department_id' => 22),
			array('name' => "El Rosario",'department_id' => 22),
			array('name' => "El Tablon",'department_id' => 22),
			array('name' => "El Tambo",'department_id' => 22),
			array('name' => "Funes",'department_id' => 22),
			array('name' => "Guachucal",'department_id' => 22),
			array('name' => "Guaitarilla",'department_id' => 22),
			array('name' => "Gualmatan",'department_id' => 22),
			array('name' => "Iles",'department_id' => 22),
			array('name' => "Imues",'department_id' => 22),
			array('name' => "Ipiales",'department_id' => 22),
			array('name' => "La Cruz",'department_id' => 22),
			array('name' => "La Florida",'department_id' => 22),
			array('name' => "La Llanada",'department_id' => 22),
			array('name' => "La Tola",'department_id' => 22),
			array('name' => "La Union",'department_id' => 22),
			array('name' => "Leiva",'department_id' => 22),
			array('name' => "Linares",'department_id' => 22),
			array('name' => "Los Andes",'department_id' => 22),
			array('name' => "Magui",'department_id' => 22),
			array('name' => "Mallama",'department_id' => 22),
			array('name' => "Mosquera",'department_id' => 22),
			array('name' => "Narino",'department_id' => 22),
			array('name' => "Olaya Herrera",'department_id' => 22),
			array('name' => "Ospina",'department_id' => 22),
			array('name' => "Pasto",'department_id' => 22),
			array('name' => "Pizarro",'department_id' => 22),
			array('name' => "Policarpa",'department_id' => 22),
			array('name' => "Potosi",'department_id' => 22),
			array('name' => "Providencia",'department_id' => 22),
			array('name' => "Puerres",'department_id' => 22),
			array('name' => "Pupiales",'department_id' => 22),
			array('name' => "Ricaurte",'department_id' => 22),
			array('name' => "Roberto Payan",'department_id' => 22),
			array('name' => "Samaniego",'department_id' => 22),
			array('name' => "San Bernardo",'department_id' => 22),
			array('name' => "San Lorenzo",'department_id' => 22),
			array('name' => "San Pablo",'department_id' => 22),
			array('name' => "San Pedro de Cartago",'department_id' => 22),
			array('name' => "Sandona",'department_id' => 22),
			array('name' => "Santa Barbara",'department_id' => 22),
			array('name' => "Santacruz",'department_id' => 22),
			array('name' => "Sapuyes",'department_id' => 22),
			array('name' => "Taminango",'department_id' => 22),
			array('name' => "Tangua",'department_id' => 22),
			array('name' => "Tumaco",'department_id' => 22),
			array('name' => "Tuquerres",'department_id' => 22),
			array('name' => "Yacuanquer",'department_id' => 22),

			array('name' => "Abrego",'department_id' => 23),
			array('name' => "Arboledas",'department_id' => 23),
			array('name' => "Bochalema",'department_id' => 23),
			array('name' => "Bucarasica",'department_id' => 23),
			array('name' => "Cachira",'department_id' => 23),
			array('name' => "Cacota",'department_id' => 23),
			array('name' => "Chinacota",'department_id' => 23),
			array('name' => "Chitaga",'department_id' => 23),
			array('name' => "Convencion",'department_id' => 23),
			array('name' => "Cucuta",'department_id' => 23),
			array('name' => "Cucutilla",'department_id' => 23),
			array('name' => "Durania",'department_id' => 23),
			array('name' => "El Carmen",'department_id' => 23),
			array('name' => "El Tarra",'department_id' => 23),
			array('name' => "El Zulia",'department_id' => 23),
			array('name' => "Gramalote",'department_id' => 23),
			array('name' => "Hacari",'department_id' => 23),
			array('name' => "Herran",'department_id' => 23),
			array('name' => "La Esperanza",'department_id' => 23),
			array('name' => "La Playa",'department_id' => 23),
			array('name' => "Labateca",'department_id' => 23),
			array('name' => "Los Patios",'department_id' => 23),
			array('name' => "Lourdes",'department_id' => 23),
			array('name' => "Mutiscua",'department_id' => 23),
			array('name' => "Ocana",'department_id' => 23),
			array('name' => "Pamplona",'department_id' => 23),
			array('name' => "Pamplonita",'department_id' => 23),
			array('name' => "Puerto Santander",'department_id' => 23),
			array('name' => "Ragonvalia",'department_id' => 23),
			array('name' => "Salazar",'department_id' => 23),
			array('name' => "San Calixto",'department_id' => 23),
			array('name' => "San Cayetano",'department_id' => 23),
			array('name' => "Santiago",'department_id' => 23),
			array('name' => "Sardinata",'department_id' => 23),
			array('name' => "Silos",'department_id' => 23),
			array('name' => "Teorama",'department_id' => 23),
			array('name' => "Tibu",'department_id' => 23),
			array('name' => "Toledo",'department_id' => 23),
			array('name' => "Villa Caro",'department_id' => 23),
			array('name' => "Villa del Rosario",'department_id' => 23), 

			array('name' => "Colon",'department_id' => 24),
			array('name' => "Mocoa",'department_id' => 24),
			array('name' => "Orito",'department_id' => 24),
			array('name' => "Puerto Asis",'department_id' => 24),
			array('name' => "Puerto Caycedo",'department_id' => 24),
			array('name' => "Puerto Guzman",'department_id' => 24),
			array('name' => "Puerto Leguizamo",'department_id' => 24),
			array('name' => "San Francisco",'department_id' => 24),
			array('name' => "San Miguel",'department_id' => 24),
			array('name' => "Santiago",'department_id' => 24),
			array('name' => "Sibundoy",'department_id' => 24),
			array('name' => "Valle del Guamuez",'department_id' => 24),
			array('name' => "Villagarzon",'department_id' => 24),

			array('name' => "Armenia",'department_id' => 25),
			array('name' => "Buenavista",'department_id' => 25),
			array('name' => "Calarca",'department_id' => 25),
			array('name' => "Circasia",'department_id' => 25),
			array('name' => "Cordoba",'department_id' => 25),
			array('name' => "Filandia",'department_id' => 25),
			array('name' => "Genova",'department_id' => 25),
			array('name' => "La Tebaida",'department_id' => 25),
			array('name' => "Montenegro",'department_id' => 25),
			array('name' => "Pijao",'department_id' => 25),
			array('name' => "Quimbaya",'department_id' => 25),
			array('name' => "Salento",'department_id' => 25),

			array('name' => "Apia",'department_id' => 26),
			array('name' => "Balboa",'department_id' => 26),
			array('name' => "Belen de Umbria",'department_id' => 26),
			array('name' => "Dos Quebradas",'department_id' => 26),
			array('name' => "Guatica",'department_id' => 26),
			array('name' => "La Celia",'department_id' => 26),
			array('name' => "La Virginia",'department_id' => 26),
			array('name' => "Marsella",'department_id' => 26),
			array('name' => "Mistrato",'department_id' => 26),
			array('name' => "Pereira",'department_id' => 26),
			array('name' => "Pueblo Rico",'department_id' => 26),
			array('name' => "Quinchia",'department_id' => 26),
			array('name' => "Santa Rosa de Cabal",'department_id' => 26),
			array('name' => "Santuario",'department_id' => 26),

			array('name' => "Providencia y Santa Catalina",'department_id' => 27),
			array('name' => "San Andrés",'department_id' => 27),

			array('name' => "Aguada",'department_id' => 28),
			array('name' => "Albania",'department_id' => 28),
			array('name' => "Aratoca",'department_id' => 28),
			array('name' => "Barbosa",'department_id' => 28),
			array('name' => "Barichara",'department_id' => 28),
			array('name' => "Barrancabermeja",'department_id' => 28),
			array('name' => "Betulia",'department_id' => 28),
			array('name' => "Bolivar",'department_id' => 28),
			array('name' => "Bucaramanga",'department_id' => 28),
			array('name' => "Cabrera",'department_id' => 28),
			array('name' => "California",'department_id' => 28),
			array('name' => "Capitanejo",'department_id' => 28),
			array('name' => "Carcasi",'department_id' => 28),
			array('name' => "Cepita",'department_id' => 28),
			array('name' => "Cerrito",'department_id' => 28),
			array('name' => "Charala",'department_id' => 28),
			array('name' => "Charta",'department_id' => 28),
			array('name' => "Chima",'department_id' => 28),
			array('name' => "Chipata",'department_id' => 28),
			array('name' => "Cimitarra",'department_id' => 28),
			array('name' => "Concepcion",'department_id' => 28),
			array('name' => "Confines",'department_id' => 28),
			array('name' => "Contratacion",'department_id' => 28),
			array('name' => "Coromoro",'department_id' => 28),
			array('name' => "Curiti",'department_id' => 28),
			array('name' => "El Carmen",'department_id' => 28),
			array('name' => "El Guacamayo",'department_id' => 28),
			array('name' => "El Penon",'department_id' => 28),
			array('name' => "El Playon",'department_id' => 28),
			array('name' => "Encino",'department_id' => 28),
			array('name' => "Enciso",'department_id' => 28),
			array('name' => "Florian",'department_id' => 28),
			array('name' => "Floridablanca",'department_id' => 28),
			array('name' => "Galan",'department_id' => 28),
			array('name' => "Gambita",'department_id' => 28),
			array('name' => "Giron",'department_id' => 28),
			array('name' => "Guaca",'department_id' => 28),
			array('name' => "Guadalupe",'department_id' => 28),
			array('name' => "Guapota",'department_id' => 28),
			array('name' => "Guavata",'department_id' => 28),
			array('name' => "Guepsa",'department_id' => 28),
			array('name' => "Hato",'department_id' => 28),
			array('name' => "Jesus Maria",'department_id' => 28),
			array('name' => "Jordan",'department_id' => 28),
			array('name' => "La Belleza",'department_id' => 28),
			array('name' => "La Paz",'department_id' => 28),
			array('name' => "Landazuri",'department_id' => 28),
			array('name' => "Lebrija",'department_id' => 28),
			array('name' => "Los Santos",'department_id' => 28),
			array('name' => "Macaravita",'department_id' => 28),
			array('name' => "Malaga",'department_id' => 28),
			array('name' => "Matanza",'department_id' => 28),
			array('name' => "Mogotes",'department_id' => 28),
			array('name' => "Molagavita",'department_id' => 28),
			array('name' => "Ocamonte",'department_id' => 28),
			array('name' => "Oiba",'department_id' => 28),
			array('name' => "Onzaga",'department_id' => 28),
			array('name' => "Palmar",'department_id' => 28),
			array('name' => "Palmas del Socorro",'department_id' => 28),
			array('name' => "Paramo",'department_id' => 28),
			array('name' => "Piedecuesta",'department_id' => 28),
			array('name' => "Pinchote",'department_id' => 28),
			array('name' => "Puente Nacional",'department_id' => 28),
			array('name' => "Puerto Parra",'department_id' => 28),
			array('name' => "Puerto Wilches",'department_id' => 28),
			array('name' => "Rionegro",'department_id' => 28),
			array('name' => "Sabana de Torres",'department_id' => 28),
			array('name' => "San Andres",'department_id' => 28),
			array('name' => "San Benito",'department_id' => 28),
			array('name' => "San Gil",'department_id' => 28),
			array('name' => "San Joaquin",'department_id' => 28),
			array('name' => "San Jose de Miranda",'department_id' => 28),
			array('name' => "San Miguel",'department_id' => 28),
			array('name' => "San Vicente de Chucuri",'department_id' => 28),
			array('name' => "Santa Barbara",'department_id' => 28),
			array('name' => "Santa Helena",'department_id' => 28),
			array('name' => "Simacota",'department_id' => 28),
			array('name' => "Socorro",'department_id' => 28),
			array('name' => "Suaita",'department_id' => 28),
			array('name' => "Sucre",'department_id' => 28),
			array('name' => "Surata",'department_id' => 28),
			array('name' => "Tona",'department_id' => 28),
			array('name' => "Valle San Jose",'department_id' => 28),
			array('name' => "Velez",'department_id' => 28),
			array('name' => "Vetas",'department_id' => 28),
			array('name' => "Villanueva",'department_id' => 28),
			array('name' => "Zapatoca",'department_id' => 28),

			array('name' => "Buenavista",'department_id' => 29),
			array('name' => "Caimito",'department_id' => 29),
			array('name' => "Chalan",'department_id' => 29),
			array('name' => "Coloso",'department_id' => 29),
			array('name' => "Corozal",'department_id' => 29),
			array('name' => "El Roble",'department_id' => 29),
			array('name' => "Galeras",'department_id' => 29),
			array('name' => "Guaranda",'department_id' => 29),
			array('name' => "La Union",'department_id' => 29),
			array('name' => "Los Palmitos",'department_id' => 29),
			array('name' => "Majagual",'department_id' => 29),
			array('name' => "Morroa",'department_id' => 29),
			array('name' => "Ovejas",'department_id' => 29),
			array('name' => "Palmito",'department_id' => 29),
			array('name' => "Sampues",'department_id' => 29),
			array('name' => "San Benito Abad",'department_id' => 29),
			array('name' => "San Juan de Betulia",'department_id' => 29),
			array('name' => "San Marcos",'department_id' => 29),
			array('name' => "San Onofre",'department_id' => 29),
			array('name' => "San Pedro",'department_id' => 29),
			array('name' => "Since",'department_id' => 29),
			array('name' => "Sincelejo",'department_id' => 29),
			array('name' => "Sucre",'department_id' => 29),
			array('name' => "Tolu",'department_id' => 29),
			array('name' => "Toluviejo",'department_id' => 29),

			array('name' => "Alpujarra",'department_id' => 30),
			array('name' => "Alvarado",'department_id' => 30),
			array('name' => "Ambalema",'department_id' => 30),
			array('name' => "Anzoategui",'department_id' => 30),
			array('name' => "Ataco",'department_id' => 30),
			array('name' => "Cajamarca",'department_id' => 30),
			array('name' => "Carmen de Apicala",'department_id' => 30),
			array('name' => "Casabianca",'department_id' => 30),
			array('name' => "Chaparral",'department_id' => 30),
			array('name' => "Coello",'department_id' => 30),
			array('name' => "Coyaima",'department_id' => 30),
			array('name' => "Cunday",'department_id' => 30),
			array('name' => "Dolores",'department_id' => 30),
			array('name' => "Espinal",'department_id' => 30),
			array('name' => "Falan",'department_id' => 30),
			array('name' => "Flandes",'department_id' => 30),
			array('name' => "Fresno",'department_id' => 30),
			array('name' => "Guamo",'department_id' => 30),
			array('name' => "Guayabal",'department_id' => 30),
			array('name' => "Herveo",'department_id' => 30),
			array('name' => "Honda",'department_id' => 30),
			array('name' => "Ibague",'department_id' => 30),
			array('name' => "Icononzo",'department_id' => 30),
			array('name' => "Lerida",'department_id' => 30),
			array('name' => "Libano",'department_id' => 30),
			array('name' => "Mariquita",'department_id' => 30),
			array('name' => "Melgar",'department_id' => 30),
			array('name' => "Murillo",'department_id' => 30),
			array('name' => "Natagaima",'department_id' => 30),
			array('name' => "Ortega",'department_id' => 30),
			array('name' => "Palocabildo",'department_id' => 30),
			array('name' => "Piedras",'department_id' => 30),
			array('name' => "Planadas",'department_id' => 30),
			array('name' => "Prado",'department_id' => 30),
			array('name' => "Purificacion",'department_id' => 30),
			array('name' => "Rioblanco",'department_id' => 30),
			array('name' => "Roncesvalles",'department_id' => 30),
			array('name' => "Rovira",'department_id' => 30),
			array('name' => "Saldana",'department_id' => 30),
			array('name' => "San Antonio",'department_id' => 30),
			array('name' => "San Luis",'department_id' => 30),
			array('name' => "Santa Isabel",'department_id' => 30),
			array('name' => "Suarez",'department_id' => 30),
			array('name' => "Valle de San Juan",'department_id' => 30),
			array('name' => "Venadillo",'department_id' => 30),
			array('name' => "Villahermosa",'department_id' => 30),
			array('name' => "Villarrica",'department_id' => 30),

			array('name' => "Alcala",'department_id' => 31),
			array('name' => "Andalucia",'department_id' => 31),
			array('name' => "Ansermanuevo",'department_id' => 31),
			array('name' => "Argelia",'department_id' => 31),
			array('name' => "Bolivar",'department_id' => 31),
			array('name' => "Buenaventura",'department_id' => 31),
			array('name' => "Buga",'department_id' => 31),
			array('name' => "Bugalagrande",'department_id' => 31),
			array('name' => "Caicedonia",'department_id' => 31),
			array('name' => "Cali",'department_id' => 31),
			array('name' => "Calima",'department_id' => 31),
			array('name' => "Candelaria",'department_id' => 31),
			array('name' => "Cartago",'department_id' => 31),
			array('name' => "Dagua",'department_id' => 31),
			array('name' => "El Aguila",'department_id' => 31),
			array('name' => "El Cairo",'department_id' => 31),
			array('name' => "El Cerrito",'department_id' => 31),
			array('name' => "El Dovio",'department_id' => 31),
			array('name' => "Florida",'department_id' => 31),
			array('name' => "Ginebra",'department_id' => 31),
			array('name' => "Guacari",'department_id' => 31),
			array('name' => "Jamundi",'department_id' => 31),
			array('name' => "La Cumbre",'department_id' => 31),
			array('name' => "La Union",'department_id' => 31),
			array('name' => "La Victoria",'department_id' => 31),
			array('name' => "Obando",'department_id' => 31),
			array('name' => "Palmira",'department_id' => 31),
			array('name' => "Pradera",'department_id' => 31),
			array('name' => "Restrepo",'department_id' => 31),
			array('name' => "Riofrio",'department_id' => 31),
			array('name' => "Roldanillo",'department_id' => 31),
			array('name' => "San Pedro",'department_id' => 31),
			array('name' => "Sevilla",'department_id' => 31),
			array('name' => "Toro",'department_id' => 31),
			array('name' => "Trujillo",'department_id' => 31),
			array('name' => "Tulua",'department_id' => 31),
			array('name' => "Ulloa",'department_id' => 31),
			array('name' => "Versalles",'department_id' => 31),
			array('name' => "Vijes",'department_id' => 31),
			array('name' => "Yotoco",'department_id' => 31),
			array('name' => "Yumbo",'department_id' => 31),
			array('name' => "Zarzal",'department_id' => 31),

			array('name' => "Caruru",'department_id' => 32),
			array('name' => "Mitu",'department_id' => 32),
			array('name' => "Pacoa",'department_id' => 32),
			array('name' => "Papunaua",'department_id' => 32),
			array('name' => "Taraira",'department_id' => 32),
			array('name' => "Yavarate",'department_id' => 32),

			array('name' => "Yavarate",'department_id' => 33),
			array('name' => "La Primavera",'department_id' => 33),
			array('name' => "Puerto Carreño",'department_id' => 33),
			array('name' => "Santa Rosalia",'department_id' => 33)
		);
		DB::table('cities')->insert($cities);
    }
}
